# Generated by Django 4.0.4 on 2022-06-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0002_alter_cliente_telefcliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del Producto')),
                ('nomProducto', models.CharField(max_length=30, verbose_name='NombreP')),
                ('precioProducto', models.IntegerField(verbose_name='Precio')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombreCliente',
            field=models.CharField(max_length=20, verbose_name='NombreC'),
        ),
    ]
