# Generated by Django 4.0.4 on 2022-06-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0003_producto_alter_cliente_nombrecliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Descripcion',
            field=models.CharField(default=1, max_length=20, verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
